name: Build

on:
  push:
    branches:
      - main
      - DEV-115_deployment-on-aws
  pull_request:
    branches: [ $default_branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Process the CSS with Tailwind

    steps:
    - uses: actions/checkout@v2

    - name: Set version number
      id: version
      uses: DEalog/version-action@v0.1.0
      with:
        fallback-prefix: ""

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Use cached node_modules
      id: cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: nodeModules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nodeModules-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Process the CSS
      run: npx tailwindcss build app.css -o css/styles.css`
      env:
        NODE_ENV: production