# good to know: https://stackoverflow.com/a/65081720/790879
name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy to Amazon S3 develop
    if: startsWith(github.event.workflow_run.head_branch, 'DEV-')

    env:
      AWS_REGION: eu-central-1
      S3_BUCKET: dev.dealog.de

    steps:
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync with S3 (dev)
        run: aws s3 sync ./website s3://${{ env.S3_BUCKET }} --delete

  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to Amazon S3 production
    if: github.event.workflow_run.head_branch == 'main'

    env:
      AWS_REGION: eu-central-1
      S3_BUCKET: www.dealog.de

    steps:
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Sync with S3 (production)
        run: aws s3 sync ./website s3://${{ env.S3_BUCKET }} --delete
